# Based in: https://github.com/abarichello/godot-ci/blob/master/.gitlab-ci.yml

image: barichello/godot-ci:3.4.2

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: My-Template

before_script:
  - cd 'Template'
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - mkdir -v -p build/web

linux:
  stage: export
  script:
    - godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  script:
    - godot -v --export "Mac OSX" ./build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac

web:
  stage: export
  script:
    - godot -v --export "HTML5" ./build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web

# GitLab Pages Deploy
pages:
  stage: deploy
  dependencies:
    - web
  script:
    - git checkout pages
    - rm -f *.md
    - mv build/web/** ./public
  artifacts:
    paths:
      - public
