# Base: https://gitlab.com/barichello/game-off/-/blob/master/.gitlab-ci.yml

image: barichello/godot-ci:mono-3.5.1

pipelines:
  branches:
    master:
      - step:
          name: "Clear"
          script:
            - rm -rf build
            - rm -rf .import

      - parallel:
          - step:
              name: "Web Export"
              #trigger: manual
              script:
                - mkdir -v -p ./build/web
                - cd $FOLDER_PATH
                - godot -v --export "HTML5" ../build/web/index.html
              artifacts:
                - build/web/**

          - step:
              name: "Windows Export"
              #trigger: manual
              script:
                - mkdir -v -p ./build/windows
                - cd $FOLDER_PATH
                - godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
              artifacts:
                - build/windows/**

          - step:
              name: "Linux Export"
              #trigger: manual
              script:
                - mkdir -v -p ./build/linux
                - cd $FOLDER_PATH
                - godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
              artifacts:
                - build/linux/**

          - step:
              name: "Mac Export"
              #trigger: manual
              script:
                - mkdir -v -p ./build/mac
                - cd $FOLDER_PATH
                - godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
              artifacts:
                - build/mac/**

      - step:
          name: "Artifact All"
          #trigger: manual
          script:
            - echo "Artifact All."
          artifacts:
            - build/**
